# RL Chess Engine Training Configuration
learning_rate: 0.0001
batch_size: 128
num_episodes: 5000
replay_buffer_size: 10000
move_penalty: -0.01
epsilon: 0.2
discount: 0.99
model_save_path: chess_rl_model.pth
log_file: rl_train.log
use_mcts: true
mcts_simulations: 20 